global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'website'
	scrape_interval: 5s
	static_configs:
      - targets: ['website:80']

  - job_name: 'prometheus'
  static_configs:
    - targets: ['localhost:9090']